import markdown
import re

# --- Read source ---
with open("kundli_report.md", "r", encoding="utf-8") as f:
    md = f.read()

# --- Regex highlighting (wrap only, no deletions) ---

# Green: strong/positive indicators
md = re.sub(
    r"(exalted|own sign|strong|beneficial|yoga|yoga active|positive)",
    r"<span class='green'>\1</span>",
    md, flags=re.IGNORECASE
)

# Red: weak/negative indicators
md = re.sub(
    r"(debilitated|dosha|afflicted|combust|weak|problem)",
    r"<span class='red'>\1</span>",
    md, flags=re.IGNORECASE
)

# Yellow: mixed/moderate indicators
md = re.sub(
    r"(mixed|moderate|neutral)",
    r"<span class='yellow'>\1</span>",
    md, flags=re.IGNORECASE
)

# --- Convert full markdown to HTML (preserves 100% content) ---
html_body = markdown.markdown(
    md,
    extensions=["tables", "toc", "fenced_code"]
)

# --- Premium HTML wrapper ---
styled_html = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Premium Kundli Report — Abhishek Singh</title>
<style>
  /* ─── Reset & base ─── */
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

  html { scroll-behavior: smooth; font-size: 16px; }

  body {
    font-family: 'Georgia', serif;
    background: #1a1209;
    color: #f0e4c8;
    line-height: 1.8;
  }

  /* ─── Layout: sidebar + main ─── */
  .layout {
    display: flex;
    min-height: 100vh;
  }

  /* ─── Sticky sidebar TOC ─── */
  .sidebar {
    width: 260px;
    min-width: 220px;
    max-width: 300px;
    background: #120d05;
    border-right: 2px solid #b8860b;
    position: sticky;
    top: 0;
    height: 100vh;
    overflow-y: auto;
    padding: 24px 16px;
    flex-shrink: 0;
  }

  .sidebar h2 {
    font-size: 0.85rem;
    text-transform: uppercase;
    letter-spacing: 2px;
    color: #d4a017;
    margin-bottom: 16px;
    padding-bottom: 8px;
    border-bottom: 1px solid #b8860b;
  }

  /* TOC generated by python-markdown */
  .sidebar .toc ul {
    list-style: none;
    padding-left: 0;
  }
  .sidebar .toc ul ul {
    padding-left: 14px;
    border-left: 1px solid #3a2a0a;
    margin-top: 4px;
  }
  .sidebar .toc li {
    margin: 4px 0;
  }
  .sidebar .toc a {
    color: #c8a86e;
    text-decoration: none;
    font-size: 0.82rem;
    line-height: 1.4;
    display: block;
    padding: 2px 4px;
    border-radius: 3px;
    transition: background 0.2s, color 0.2s;
  }
  .sidebar .toc a:hover {
    background: #2a1e08;
    color: #ffd966;
  }

  /* ─── Main content area ─── */
  .main {
    flex: 1;
    max-width: 860px;
    margin: 0 auto;
    padding: 40px 48px 80px;
  }

  /* ─── Card wrapper ─── */
  .card {
    background: #211607;
    border: 1px solid #3a2a0a;
    border-radius: 10px;
    padding: 40px 44px;
    box-shadow: 0 4px 32px rgba(0,0,0,0.6);
  }

  /* ─── Headings ─── */
  h1 {
    font-size: 2rem;
    color: #ffd966;
    border-bottom: 3px solid #b8860b;
    padding-bottom: 12px;
    margin-bottom: 24px;
    margin-top: 8px;
    letter-spacing: 0.5px;
  }
  h2 {
    font-size: 1.45rem;
    color: #e8c060;
    border-bottom: 1.5px solid #7a5c10;
    padding-bottom: 8px;
    margin-top: 48px;
    margin-bottom: 18px;
  }
  h3 {
    font-size: 1.15rem;
    color: #d4a855;
    margin-top: 32px;
    margin-bottom: 12px;
  }
  h4 {
    font-size: 1rem;
    color: #c89640;
    margin-top: 24px;
    margin-bottom: 8px;
  }
  h5, h6 {
    font-size: 0.95rem;
    color: #b08030;
    margin-top: 16px;
    margin-bottom: 6px;
  }

  /* ─── Paragraphs & lists ─── */
  p { margin-bottom: 14px; }

  ul, ol {
    margin: 10px 0 14px 24px;
  }
  li { margin-bottom: 6px; }

  /* ─── Highlight spans ─── */
  .green { color: #52c478; font-weight: bold; }
  .red   { color: #e86060; font-weight: bold; }
  .yellow{ color: #f0c040; font-weight: bold; }

  /* ─── Tables ─── */
  table {
    width: 100%;
    border-collapse: collapse;
    margin: 20px 0 28px;
    font-size: 0.9rem;
    background: #1c1005;
  }
  th {
    background: #3a2a08;
    color: #ffd966;
    font-weight: bold;
    padding: 10px 14px;
    border: 1px solid #5a420e;
    text-align: left;
  }
  td {
    padding: 8px 14px;
    border: 1px solid #3a2a0a;
    color: #e0d0b0;
    vertical-align: top;
  }
  tr:nth-child(even) td { background: #231808; }
  tr:hover td { background: #2c1e0a; }

  /* ─── Blockquotes ─── */
  blockquote {
    border-left: 4px solid #b8860b;
    margin: 16px 0;
    padding: 10px 20px;
    background: #1c1308;
    color: #d4b880;
    font-style: italic;
    border-radius: 0 6px 6px 0;
  }

  /* ─── Horizontal rules ─── */
  hr {
    border: none;
    border-top: 1px solid #3a2a0a;
    margin: 36px 0;
  }

  /* ─── Inline code ─── */
  code {
    background: #2a1e08;
    color: #ffd966;
    padding: 2px 6px;
    border-radius: 3px;
    font-family: 'Courier New', monospace;
    font-size: 0.88em;
  }

  /* ─── Strong / em ─── */
  strong { color: #ffd966; }
  em     { color: #d4a855; }

  /* ─── Scrollbar styling ─── */
  ::-webkit-scrollbar { width: 8px; }
  ::-webkit-scrollbar-track { background: #120d05; }
  ::-webkit-scrollbar-thumb { background: #5a420e; border-radius: 4px; }
  ::-webkit-scrollbar-thumb:hover { background: #b8860b; }

  /* ─── Responsive: collapse sidebar on small screens ─── */
  @media (max-width: 768px) {
    .layout { flex-direction: column; }
    .sidebar {
      position: static;
      width: 100%;
      max-width: 100%;
      height: auto;
      border-right: none;
      border-bottom: 2px solid #b8860b;
    }
    .main { padding: 24px 18px 60px; }
    .card { padding: 24px 18px; }
  }
</style>
</head>
<body>
<div class="layout">

  <!-- Sticky sidebar TOC (populated by TOC extension markers below) -->
  <nav class="sidebar">
    <h2>&#9733; Contents</h2>
    <div class="toc">
      TOC_PLACEHOLDER
    </div>
  </nav>

  <!-- Main content -->
  <main class="main">
    <div class="card">
      CONTENT_PLACEHOLDER
    </div>
  </main>

</div>
</body>
</html>
"""

# The python-markdown `toc` extension injects a [TOC] div into the body HTML.
# We extract it for the sidebar and keep the rest as the card body.
toc_div_match = re.search(r'<div class="toc">(.*?)</div>', html_body, re.DOTALL)
if toc_div_match:
    toc_html = toc_div_match.group(1)
    # Remove the toc div from main body to avoid duplication
    html_body_clean = html_body[:toc_div_match.start()] + html_body[toc_div_match.end():]
else:
    toc_html = "<p><em>No headings found.</em></p>"
    html_body_clean = html_body

final_html = styled_html.replace("TOC_PLACEHOLDER", toc_html)
final_html = final_html.replace("CONTENT_PLACEHOLDER", html_body_clean)

with open("kundli_report.html", "w", encoding="utf-8") as f:
    f.write(final_html)

print(f"Done. Output: kundli_report.html ({len(final_html):,} chars)")
